### ISSUE TITLE
Can't open Google Drive subdirectories -- server error: the folder/file does not exist

### ISSUE THREAD

**Issue by kevinsullivan** [jupyter/jupyter-drive#122]
I've successfully installed JD, have authenticated to GD, and can see my top-level GD directory. I can drill down into one subdirectory, and I can see the files and sub-sub-directories. However I'm unable to open any of the sub-sub-directories. Whenever I try I can see JD using the GD APIs, but after 20 or 30 secs I seem to get a timeout and then this server error failure. Any ideas? I apologize for not being equipped to debug the problem myself.

**Comment by kevinsullivan** [comment]
I've now installed Jupyter in --mixed mode, so that I can access notebooks both on Google drive and on my local machine. I can open, edit, and save notebooks on /local but I'm still unable to open gdrive files. Here's the error I'm getting now. 

The error was:
TypeError: this.metadata is undefined
See the error console for details.

**Comment by Carreau** [comment]
I'll dig into that too tomorrow.

**Comment by Carreau** [comment]
Ok, that was actually a completely insane behavior of javascript. #124 should fix that too. 

Basically, if you have `/folder/subfolder/file` and you ask javascript the following:

```
parent = root
for(pth in path.split('/')){
    parent = get(pth)
}
retrurn parent
```

`pth` will be shared across ll loops, leading roughtly to the first call beeing actually effected beeing `root.get('file')` which obviously fails.

**Comment by Carreau** [comment]
This should be fixed now.
