### ISSUE TITLE
Can't back out of "python -m jupyterdrive" to add "--mixed"

### ISSUE THREAD

**Issue by kevinsullivan** [jupyter/jupyter-drive#123]
Hi folks,

I inadvertently executed "python -m jupyterdrive" rather than "python -m jupyterdrive --mixed", and now I can't figure out what persistent state is causing me to be unable to do "python -m jupyterdrive --mixed." 
The problem appears to be revealed by these lines of code

 with jconfig(profile) as config:
        if 'NotebookApp' in config:
            if (config['NotebookApp'].get('tornado_setting',{})) or (config['NotebookApp'].get('contents_manager_class',{})):
                # TODO, manually merge tornado setting if exist
                # but cannot do anything automatically if contents_manager_class is set
                raise ValueError('You already got some configuration that will conflict with google drive. Bailin out')

I've deleted all the jupy* files in /usr/local/lib/.... I've uninstalled and reinstalled python3, ipython, etc. Perhaps someone can tell me what I need to do to clear the config['NotebookApp'] state so that I can install jupyter in mixed mode?

I'm trying to set up a VM for student use this fall.

Thanks!
KS

**Comment by KesterTong** [comment]
The other state that needs to be removed is in the ipython profile
directory.  I think this is usually at ~/.ipython/profile_default.
@Carreau what files need to be deleted to reset the profile?

**Comment by Carreau** [comment]
`notebook_config.json` should have most of the drive-relevant config with `nbconfig/*`. I'll take a look, I'm flying back to berkeley in acouple of hours.

**Comment by kevinsullivan** [comment]
It does look like the contents of notebook_config.json are what's causing the re-install to bork. Can you advise on what to do with that file? Modify contents? Delete? Thanks! --KS

**Comment by Carreau** [comment]
You should be able to just delete it, it should work. I'm back in Berkeley I'll try to work on that today, if I can get enough of my backlog done.

**Comment by kevinsullivan** [comment]
I tried deleting ~/.ipython/profile_default (as advised). But now I get this when I 

 ... File "/home/cs1/System/jupyter-drive/jupyterdrive/__init__.py", line 95, in _activate
    with jconfig(profile) as config:
  File "/home/cs1/System/jupyter-drive/jupyterdrive/__init__.py", line 65, in __enter__
    self.pdir = locate_profile(self.profile)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/path.py", line 361, in locate_profile
    raise IOError("Couldn't find profile %r" % profile)
OSError: Couldn't find profile 'default'

**Comment by Carreau** [comment]
do `$ ipython profile create` to recreate the default profile, and re-issue `$ python -m jupyterdrive`. 

There seem to be an error in typescript compiler/gulp-tsc where the following does not raise:

```
function f(...):SomethingNotNull {
    return;
}
```

Trying to track that down.

**Comment by Carreau** [comment]
`python3 -m jupyterdrive  --deactivate` should remove the current configuration, and allow you to activate with `--mixed`. There is still some tyescript issue though,

**Comment by kevinsullivan** [comment]
Ok, thank you very much for that. It worked. When 'ipython notebook' opens I now get both directories. However, I'm still unable to open/create/save files on gdrive, per #122.
