### ISSUE TITLE
Daily Limit for Unauthenticated Use Exceeded. Continue use requires signup.

### ISSUE THREAD

**Issue by ryukinix** [jupyter/jupyter-drive#127]
### After long edit i ever receive that message and i can't save my notebook!

![image](https://cloud.githubusercontent.com/assets/7642878/10401337/baea1416-6e94-11e5-9a96-e4a5450edfb0.png)
### Details | Comment

I using `mixed content` configuration. After that message, if I close my notebook and open again, I can save him! I use linux and I don't have a good client for sync — actually, now I using `grive` but I have some bugs with shared folders (and the notebooks are shared). So the best way to save my notebooks would be `jupyter-drive`, however, I have suffering with that behavior! :cry: 
### Help

Somebody knows the reason for that? Because I really already sign in with my account. It's weird. I think that tool is very cool... i don't for sure if the bug is with `jupyter-drive` or instead some configuration mine.

Anyway, thanks for the tool, it's really useful (perhaps I guess would have better docs for installation)

**Comment by ryukinix** [comment]
### BTW, I can't make a local backup (download or even print) after that behavior T_T
![image](https://cloud.githubusercontent.com/assets/7642878/10401708/02dc0c00-6e97-11e5-9128-74286ae71500.png) 
Comment: this is a traceback of ipython notebook local server

**Comment by Carreau** [comment]
Hum that's weird. It should be authenticated. I'll try to investigate.

**Comment by KesterTong** [comment]
@Carreau The main API calls are authenticated.  Maybe a few calls are not (like the one to FilePicker when we force a user to "pick" a file if it isn't authorized under drive.file scope).

**Comment by jdfreder** [comment]
I actually see this when I'm just sitting on the dashboard for a long time.

**Comment by weilinear** [comment]
It also happens to me: sometimes have to open the same file in a new tab and do a manual line by line diff. Are there some workarounds for this? I will also try to see if I could help on this :)

**Comment by BenjaminKay** [comment]
It is also happening to me. Jupyter_Drive version  Version 1.1.0. Anaconda. Python 3.4

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).
