### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jaredvacanti** [jupyter/jupyter-drive#128]
When following the readme exactly, cloning the repo and running `python -m jupyterdrive` I get the error
```
No module named nbextensions; 'jupyterdrive' is a package and cannot be directly executed
```

Has the installation procedure changed since the last release?

**Comment by kaleemsagard** [comment]
I have that problem today, but did the following steps and it works fine:

- Uninstall IPython, jupyter drive and all similar modules/packages from SO, to start from zero.
- Install "jupyter": sudo pip install jupyter
- Install "terminado" (it was locking by version compat): sudo pip search terminado
- Install "functools32" (jupyter need it to use python 3.2 functions): sudo pip install functools32
- Upgrade "pyzmq" (my version was not fits to jupyter): sudo pip install pyzmq --upgrade
- Install "jupyter-drive" (as described in this site): sudo pip install -e jupyter-drive
- Enable jupyter-drive: python -m jupyterdrive --mixed
- Run jupyter: ipython notebook (o jupyter notebook maybe works)
- At open on browser do the respective auth on Google...

I expect that steps works for you.

**Comment by jaredvacanti** [comment]
Yea, that fixed the problem. Not sure which step was the issue.
