### ISSUE TITLE
Collaborative Editing

### ISSUE THREAD

**Issue by jaredvacanti** [jupyter/jupyter-drive#130]
Is there a way to use the drive features with a remote kernel so two simultaneous users can see edits made in real time while also seeing the computation done by the other user?

**Comment by Carreau** [comment]
Not with jupyter drive, no we need to rewrite the notebook frontend for that. 
We have a few prototypes, but they are not close to be released. 

Once collaborative edittign is supported you will have annouce on IPython/Jupyter mailing list.

**Comment by psychemedia** [comment]
Is there a roadmap somewhere giving an indicative time for when live collaborative support may be available? 3 months? 6 months? A year?

**Comment by Carreau** [comment]
Likely not 3 month, You might see dev version with some feature in 6month, probably some things in a year. Right now we focus on getting notebook 4.1 out, and pushing for 2 new hires to work more on that starting January.
