### ISSUE TITLE
Constant requests for authentication

### ISSUE THREAD

**Issue by philipsd6** [jupyter/jupyter-drive#141]
I've got `jupyter-drive` configured in mixed mode on my Jupyter Hub setup. I've created my own Google project for this in order to use my own **CLIENT_ID**. My `~/.jupyter/nbconfig/common.json` contains:

```json
  "gdrive": {
    "METADATA_SCOPE": true,
    "FILE_SCOPE": true,
    "CLIENT_ID": "123451234512-asdlfkjhadslfkjhaldskjfhaldskjfha.apps.googleusercontent.com"
  },
```
It *kinda* works. With this setup, I'm prompted to authenticate with Google when first launched. The OAuth window pops up but disappears immediately, presumably because I've already authenticated with Google. The directory or Notebook is loaded ok. The problem is every time I click on a folder or notebook to load, I am re-prompted for authentication -- *even* if I'm working under `/local`. 

Why isn't it remembering my authentication?

**Comment by paulsp94** [comment]
Hey philips, I encountered the same problem. Did you find any solution for it?

**Comment by philipsd6** [comment]
I just set this up again on my WSL setup and this is still happening, even without customizing common.json with my own client_id. I don't know why. It's disheartening that this bug report hasn't been answered for 7 months.

**Comment by ian-r-rose** [comment]
Hi @philipsd6, sorry to hear you are having trouble with this. I am not sure what is causing the issue that you are running into, but the integration with Google Drive provided by `jupyter-drive` is being deprecated in favor of the plugin for JupyterLab, [`jupyterlab-google-drive`](https://github.com/jupyterlab/jupyterlab-google-drive). Given our limited developer resources, we have not been able to put much time into this project recently.

**Comment by philipsd6** [comment]
Yes, I just heard about this, and so I installed Jupyterlab and jupyterlab-google-drive, but continue to have new and exciting problems, so I had to open up an issue there as well.

**Comment by Carreau** [comment]
> Yes, I just heard about this, and so I installed Jupyterlab and jupyterlab-google-drive, but continue to have new and exciting problems, so I had to open up an issue there as wel

Try deactivating any privacy / blocking extensions, we need to set cookies w/ google and cross domain, if an extension is messing with that that could be the reason.

**Comment by philipsd6** [comment]
Yes, that *is* the problem, confirmed by disabling Privacy Badger and uBlock Origin, however, as those are installed by corporate group policy, I cannot keep them disabled for long before they are automatically re-enabled and then this fails.

**Comment by Carreau** [comment]
> Yes, that is the problem, confirmed by disabling Privacy Badger and uBlock Origin, however, as those are installed by corporate group policy, I cannot keep them disabled for long before they are automatically re-enabled and then this fails.

You should be able to setup/Ask for an exception to be made in the app configuration for the pair (url-of-jupyter/google-api).

**Comment by philipsd6** [comment]
as I have Admin on my laptop, I'm more comfortable taking matters into my own hands. ;)
