### ISSUE TITLE
Issue for Loading Jupyter Notebook in Google Drive Colab

### ISSUE THREAD

**Issue by wushengzhong** [jupyter/jupyter-drive#144]
I run into issue when loading jupyter notebook in Google drive colab every time I closed and open again. It just keeps displaying the message below. Could anyone know the reason why?

`Loading... Try our new GPU accelerated runtime`

**Comment by takluyver** [comment]
Sorry, you'll have to ask Google about that. We don't run Colaboratory. `jupyter-drive` is a separate project which hasn't been actively developed for a couple of years.

From the FAQ:

> I found a bug or have a question, who do I contact?
> Open any Colaboratory notebook. Then go to the Help menu and select ”Send feedback...”.
