### ISSUE TITLE
Ability to open files that haven't been created by the App

### ISSUE THREAD

**Issue by KesterTong** [jupyter/jupyter-drive#19]
Because drive.file permission is being used, a file can only be opened if it has been created by the app, or opened with the App in either the Google Drive website, or using the FilePicker API.

Currently the FilePicker API won't work very well because it only allows one origin (e.g. 127.0.0.1:8888).  Similarly opening a file from the Google Drive website will always redirect to 127.0.0.1:8888.  Still, this is better than nothing.

**Comment by KesterTong** [comment]
@Carreau can you set of the Drive SDK for our Cloud project?  I think @minrk or @rgbkrk knows how to do this.  From the Cloud Console, go to "APIs and Auth > APIs" in the left pane, then click the gear icon next to "Drive SDK" then "original console".  Fill in the necessary fields, most important being "Open URL (required)" which should be set to 127.0.0.1:8888.  Note that until a Google API issue is fixed (they are working on it) we won't be able to open files created by other apps except when running on port 8888 and on 127.0.0.1.

**Comment by Carreau** [comment]
I don't have access apparently.

**Comment by KesterTong** [comment]
Who set up the new client ID?  Was it @rgbkrk?

**Comment by rgbkrk** [comment]
You have to do it from the project jupyter gmail account.

**Comment by Carreau** [comment]
I'm leaning on requiring minimal permissions, and asking for more permission if necessary. 
Like inserting in a menu "full drive access" warn that full access cannot be revoked except by disconnecting the app and that having access to file again is possible only with full access.

**Comment by KesterTong** [comment]
Just to be clear, what I'm proposing isn't a new kind of permission.  It's just using the drive.file scope in a different way.  Drive.file scope allows you to open any file created by the app, and also any file "opened" by the app, for a somewhat strange definition of "open".  To open a file, means to open it in the Google Drive website with your app, or in a "FilePicker", which is something you embed in your app that lets the user pick a file.  So what I'm proposing is to show FickPicker (which is like an open dialog) with a single file in it, when the user tries to open a file they don't already have permission to open.

If you're suggesting getting around all these problems by using full drive scope, then I think we need to exhaust all possible options with drive.file before we consider that, because full drive scope is much more problematic from the security perspective.

**Comment by KesterTong** [comment]
Will be fixed by #59.  Seems to work already without any changes to the Drive SDK settings.

**Comment by KesterTong** [comment]
@Carreau actually nothing needs to be done in the Drive SDK settings now.  The FilePicker is now completely independent of the Drive SDK settings.

**Comment by Carreau** [comment]
Closed by #59
