### ISSUE TITLE
Shared Content Manager

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter-drive#43]
Investigate share content manager.

**Comment by KesterTong** [comment]
accidentally hit close

**Comment by rgbkrk** [comment]
What does this one mean? I'm kind of wondering about if there was a way to bring in notebooks from other people (you're at a tutorial, want to run through someone else's notebooks, etc.).

**Comment by KesterTong** [comment]
This isn't related.  "Shared" refers to having a content manager that shows content from both drive and local (hard disk) content, so that the user doesn't have to keep switching.  Feel free to open another issue if #21 isn't broad enough.

**Comment by KesterTong** [comment]
@Carreau (responding to comment in #72)

We could either have local content starting at ```/``` while Drive content starts at ```gdrive/```, or have local content start from ```local/```.

The advantage of the first option is that it's consistent with just using the usual content manager.  When the user uses a mixed content manger set up this way, thins will look exactly the same, but there will be an extra directory called gdrive.  The advantage of the second option is that it's more uniform and consistent.  This could give us more options in the future, e.g. a completely different UX for the root directory (e.g. select from a dropdown list).

I'm open to either, don't have a strong opinion either way.

**Comment by Carreau** [comment]
I think the second option allow also a more generic mechanism to mix many contents manage wihtout having to deal with conflict. 

I'm open to either also.

**Comment by KesterTong** [comment]
Yeah avoiding conflicts is another advantage of the  second option.  Let's assume that for now.  The change on JS side for this should be very simple.  Can you start work on making the same changes on the Python side as I made on the JS side in #72?  Should be pretty much the same logic but in Python.  Then we can think about how to make it configurable.

**Comment by Carreau** [comment]
Yep will do. 

I'm working on making the installer having a `--mixed-content` option so that we can merge the mixed content into master.

**Comment by KesterTong** [comment]
Done in #79
