### ISSUE TITLE
gapi revoke some scope ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter-drive#54]
Is there a way to "revoke" some scope without having to drop all token and having to re-authorize the all thing ?

**Comment by KesterTong** [comment]
No.  In fact, last time I checked whenever you ask for any scope for a client ID, it gives all scopes that the client ID is authorized for.  E.g. if you have already given a client ID drive.file and drive.metadata.readonly scope, there is no way to get a token with just one of these scopes.

**Comment by Carreau** [comment]
> No. In fact, last time I checked whenever you ask for any scope for a client ID, it gives all scopes that the client ID is authorized for. E.g. if you have already given a client ID drive.file and drive.metadata.readonly scope, there is no way to get a token with just one of these scopes.

That's annoying.

Is there at least a way when you re-authorise an app after detaching it from drive that it still have access to old files created by it ?

**Comment by KesterTong** [comment]
Can you confirm you lose access to old files when you detach from Drive (and not just the files you lost when we change the client ID)?

If so, that is annoying but probably unfixable.  Hopefully real user's detach from drive very rarely.
