### ISSUE TITLE
Excessive calls to Drive from tree view

### ISSUE THREAD

**Issue by KesterTong** [jupyter/jupyter-drive#61]
We probably are polling Drive too frequently in tree view.  Is there a way to reduce the polling frequency (e.g. to 5 mins)?

**Comment by Carreau** [comment]
No, not configurable, should be once every minutes + on page focus. Did you focused in/out a lot?

**Comment by Carreau** [comment]
And minute time seem to stop when page is out of focus...

**Comment by KesterTong** [comment]
One minute is very high because the individual calls are very large (e.g. I have about 300 files in my Drive).  On the other hand, if it's only when the tree has focus, I guess it's not such a big deal.  Thanks for clarifying.

**Comment by Carreau** [comment]
Well if you navigate through tab quickly it might make a lot of call. I'll try if I can prevent a immediate api-call if page get focuses too often. 

Something like refresh view on focus only if last focus was more than a minute ago...

**Comment by KesterTong** [comment]
That would be perfect.

**Comment by Carreau** [comment]
IPython related PR as been merged we can now also tweak the timeing if necessary.
