### ISSUE TITLE
Tree view don't show "running" notebooks anymore. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter-drive#63]

**Comment by KesterTong** [comment]
It works for me right now.  I just pulled from IPython head (dab6a6d0d0380265f50c8718f31c909fa68d8edf)

**Comment by Carreau** [comment]
Nop really does not work for me. it does appear as running in the running tab, but not in the main one.

**Comment by Carreau** [comment]
It appears like 'list_contents' should return `running=false|true` in the model, while it does not.

**Comment by KesterTong** [comment]
That's strange that list_contents is supposed to do this.  Doesn't this create unnecessary dependencies between ContentManager and whatever managers the kernels?  Why is file management tied to kernel management like this?

**Comment by Carreau** [comment]
i might have miss understand how the code works. If kinda-works is the `model.path` does not start with `/` but there are some other issues with renaming that does not affect  the session object. I'm starting to mix things in my head.

**Comment by KesterTong** [comment]
ok now I see it.  Perhaps our code does not properly handle path names?  I was making a lot of guesses when I wrote it.  This may be the offending line: https://github.com/jupyter/jupyter-drive/blob/master/jupyterdrive/gdrive/drive-contents.js#L460

**Comment by KesterTong** [comment]
is there a path join util function we can use instead of ```var fullpath = path + '/' + resource['title'];```?

**Comment by Carreau** [comment]
> is there a path join util function we can use instead of var fullpath = path + '/' + resource['title'];?

Yes probably in utils, I'll try to have a look today. 
Sorry for the silence, the last minutes preparation stuff is crazyier than I thought.

**Comment by Carreau** [comment]
closed by #65
