### ISSUE TITLE
gapi_ready question.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter-drive#74]
I want `gapi_ready` to resolve only once things are loaded, and a specific `config()` (or named otherwise) methods is called so that `.then(authenticate)` can get access to a config object. 

Though I cannot find a way how to make it work with `Promise.all`.

Any pointer ? Or should I just change the api a lot ?

**Comment by KesterTong** [comment]
No, that's a totally reasonable thing to do (especially since calls to localhost should be quick, so it's ok to add them to the gapi_ready) promise.

It should go something like

```
var config_ready = utils.promising_ajax('http://config_url_here', {});

var gapi_ready = Promise.all([load_gapi_1().then(load_gapi_2).then(authorize), config_ready]);
```

**Comment by KesterTong** [comment]
Closing this since things were more complex than I initially thought, but you figured out how to do it anyway.
