### ISSUE TITLE
Local notebooks cannot be renamed until `mkdir ~/local` is executed

### ISSUE THREAD

**Issue by aboyett** [jupyter/jupyter-drive#88]
I logged into a jupyter-hub + sudospawner installation using github oath. My user was created and I can create a new notebook w/in the "local" namespace but any attempt to rename a notebook results in the error:
 > Unknown error renaming file: Untitled1.ipynb [Errno 2] No such file or directory: '/home/aboyett/local/foo.ipynb'

when I look at the filesystem, the notebook is actually created at `/home/aboyett/Untitled1.ipynb`, there is no `/home/aboyett/local` by default. once I create that dir the rename succeeds.

This may vary well be misconfiguration, but as far as I this installation is using a stock configuration for jupyter-hub

Details about the installation:

    > import IPython; print(IPython.sys_info())
    {'commit_hash': 'f75fda4',
     'commit_source': 'installation',
     'default_encoding': 'UTF-8',
     'ipython_path': '/usr/local/lib/python3.4/dist-packages/IPython',
     'ipython_version': '3.0.0',
     'os_name': 'posix',
     'platform': 'Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty',
     'sys_executable': '/usr/bin/python3',
     'sys_platform': 'linux',
     'sys_version': '3.4.0 (default, Apr 11 2014, 13:05:11) \n[GCC 4.8.2]'}

    $ pip3 freeze | grep -E '(ipython|jupyter)'                                                       
    ipython==3.0.0                                                                                                              
    jupyterdrive==0.9.0                                                                                                         
    jupyterhub==0.0.1-dev

`/etc/jupyterhub/jupyterhub_config.py`:

    $ cat /etc/jupyterhub/jupyterhub_config.py | grep -v -E '(^$|^#)'                                 
    c = get_config()                                                                                                            
    c.JupyterHub.authenticator_class = 'oauthenticator.LocalGitHubOAuthenticator'                                  
    <auth details elided>     

automatically created `~/.ipython/profile_default/ipython_notebook_config.json`:

    {                                                                                                                           
      "MixedContentsManager": {                                                                                                 
        "filesystem_scheme": [                                                                                                  
          {                                                                                                                     
            "contents": "IPython.html.services.contents.filemanager.FileContentsManager",                                       
            "root": "local"                                                                                                     
          },                                                                                                                    
          {                                                                                                                     
            "contents": "jupyterdrive.clientsidenbmanager.ClientSideContentsManager",                                           
            "root": "gdrive"                                                                                                    
          }                                                                                                                     
        ]                                                                                                                       
      },                                                                                                                        
      "nbformat": 1,                                                                                                            
      "NotebookApp": {                                                                                                          
        "contents_manager_class": "jupyterdrive.mixednbmanager.MixedContentsManager",                                           
        "tornado_settings": {                                                                                                   
          "contents_js_source": "nbextensions/gdrive/mixed-contents"                                                            
        }                                                                                                                       
      }                                                                                                                         
    }

automatically created `~/.ipython/profile_default/nbconfig/common.json`:

    {
      "mixed_contents": {
        "schema": [
          {
            "root": "local",
            "stripjs": false,
            "contents": "services/contents"
          },
          {
            "root": "gdrive",
            "stripjs": true,
            "contents": "./drive-contents"
          }
        ]
      }

**Comment by KesterTong** [comment]
@Carreau it looks like rename is not implemented in ```mixednbmanager.py```.  Can you add this method?  It is a bit different other methods as its signature takes two arguments which are both paths.

**Comment by Carreau** [comment]
Ok, this one was tough to track down but I think I got it. PR on it's way.
