### ISSUE TITLE
Is it possible to auto-refresh?

### ISSUE THREAD

**Issue by stared** [jupyter/jupyter-drive#96]
When two people are editing the same file, is it possible to:

* see their edits in real time? (alike in Google Docs)
* see who is logged in, which cells they are working on?

As of now, I've found that it is possible to wait for their edits and refresh browser tab, but it sounds a lot like a brute-force solution (plus, it will be easy to erase someone's else edits).

**Comment by Carreau** [comment]
This is work in progress, and is the goal of my postdoc, but it will take at least a few month. 

You are welcome to help working on that, but it's a huge piece of work. You can see some progress here:

https://github.com/jupyter/jupyter-drive/pull/90

I'll close this issues for now.

Thanks !

**Comment by stared** [comment]
Good to know! I was not sure if it was supposed to work or not. Maybe some to-do list on the readme?

In any case, thank you for your great work! :)

**Comment by Carreau** [comment]
> Maybe some to-do list on the readme

Well, Real-Time might be part of IPython itself at some point, so not sure it's worth mentionnig here for now. 

> In any case, thank you for your great work! :)

Thanks ! Anyone is welcome to contribute !
